### ISSUE TITLE
Failed to Access Stardog Server

### ISSUE THREAD

**Issue by rong0525** [CoDS-GCS/MEGR-APT-code#1]
Description:
Hello,

First of all, I would like to thank you for your excellent work. I have carefully read your paper and am very impressed with the contributions you've made. I am currently trying to run the code from this repository to further understand and learn from your work. However, I have encountered a issue when attempting to connect to the Stardog server. 

**Troubleshooting Steps Taken:**
- Checked DNS configuration and confirmed that Google's public DNS servers are being used.
- Verified network connectivity by pinging 8.8.8.8.
- Attempted to resolve the hostname using nslookup and dig, which both failed to return an IP address for the given hostname.
- Attempted to use curl and wget to connect to the server, both of which failed with DNS resolution errors.
- Confirmed that the domain sd-d63d428a.stardog.cloud does not resolve to an IP address.

**Request:**
Could you please verify if the Stardog server sd-d63d428a.stardog.cloud is currently available and properly configured? Any guidance on how to resolve this DNS issue would be greatly appreciated.

Thank you for your assistance!

**Comment by Vicitior** [comment]
Yep，I meet the same question and don't how to solve

**Comment by ahmedalyaisec** [comment]
Hello,
Thanks for your valuable feedback.
The Stardog server is currently not available,  since the subscription has expired.
You will need to set up your own Graph (Stardog) database. 
We released the RDF provenance graphs (in turtle format), so you can load them into your Stardog database instance. 
The RDF PG is available on this [link](https://drive.google.com/drive/folders/1tCIcOoP8vgQUnq6oMN_aqMo6RgdCHazD?usp=drive_link) 
You could use our Bash script `bash_src/load_to_stardog.sh` for loading. 

Regards,
